#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
v66 — Universo de selecciones nacionales del modelo internacional.

GENERADO AUTOMÁTICAMENTE por `generar_universo_selecciones.py`.
NO editar a mano: vuelve a ejecutar el generador.

Criterio: selecciones con >= 100 partidos en historico_partidos.csv (desde 1990).
Resultado: 200 selecciones (antes 49).
TEAM_STYLE: "bloque_alto" si ELO final >= 1689.8 (percentil 75), si no "bloque_bajo".
"""

# Las 49 selecciones del Mundial 2026: se conservan como subconjunto de referencia
# para poder comparar la precisión manzana-con-manzana con el modelo previo a v66.
TEAMS_MUNDIAL_2026 = [
    'MEX', 'USA', 'CAN', 'ARG', 'BRA', 'URU', 'COL', 'ECU', 'PER', 'CHI',
    'FRA', 'ENG', 'ESP', 'GER', 'ITA', 'POR', 'NED', 'BEL', 'CRO', 'SRB',
    'MAR', 'SEN', 'CMR', 'GHA', 'NGA', 'TUN', 'ALG', 'EGY', 'JPN', 'KOR',
    'IRN', 'AUS', 'KSA', 'QAT', 'CRC', 'PAN', 'HON', 'JAM', 'PAR', 'NOR',
    'SUI', 'DEN', 'AUT', 'SCO', 'CIV', 'UZB', 'JOR', 'NZL', 'CPV',
]

# 200 selecciones con historial suficiente.
TEAMS = [
    'AFG', 'ALB', 'ALG', 'AND', 'ANG', 'ARG', 'ARM', 'ATG', 'AUS', 'AUT',
    'AZE', 'BAN', 'BDI', 'BEL', 'BEN', 'BER', 'BFA', 'BHR', 'BHU', 'BIH',
    'BLR', 'BLZ', 'BOL', 'BOT', 'BRA', 'BRB', 'BRU', 'BUL', 'CAM', 'CAN',
    'CAY', 'CGO', 'CHA', 'CHI', 'CHN', 'CIV', 'CMR', 'COD', 'COL', 'COM',
    'CPV', 'CRC', 'CRO', 'CTA', 'CUB', 'CUW', 'CYP', 'CZE', 'DEN', 'DMA',
    'DOM', 'ECU', 'EGY', 'ENG', 'EQG', 'ESP', 'EST', 'ETH', 'FIJ', 'FIN',
    'FRA', 'FRO', 'GAB', 'GAM', 'GEO', 'GER', 'GGY', 'GHA', 'GIB', 'GNB',
    'GPE', 'GRE', 'GRN', 'GUA', 'GUI', 'GUM', 'GUY', 'GYF', 'HAI', 'HKG',
    'HON', 'HUN', 'IDN', 'IND', 'IRL', 'IRN', 'IRQ', 'ISL', 'ISR', 'ITA',
    'JAM', 'JEY', 'JOR', 'JPN', 'KAZ', 'KEN', 'KGZ', 'KOR', 'KSA', 'KUW',
    'KVX', 'LAO', 'LBR', 'LBY', 'LCA', 'LES', 'LIB', 'LIE', 'LTU', 'LUX',
    'LVA', 'MAC', 'MAD', 'MAR', 'MAS', 'MDA', 'MDV', 'MEX', 'MKD', 'MLI',
    'MLT', 'MNE', 'MOZ', 'MRI', 'MTN', 'MTQ', 'MWI', 'MYA', 'NAM', 'NCA',
    'NCL', 'NED', 'NEP', 'NGA', 'NIG', 'NIR', 'NOR', 'NZL', 'OMA', 'PAK',
    'PAN', 'PAR', 'PER', 'PHI', 'PLE', 'PNG', 'POL', 'POR', 'PRK', 'PUR',
    'QAT', 'ROU', 'RSA', 'RUS', 'RWA', 'SCO', 'SDN', 'SEN', 'SEY', 'SGP',
    'SKN', 'SLE', 'SLV', 'SMR', 'SOL', 'SRB', 'SRI', 'SUI', 'SUR', 'SVK',
    'SVN', 'SWE', 'SWZ', 'SYR', 'TAH', 'TAN', 'THA', 'TJK', 'TKM', 'TOG',
    'TPE', 'TRI', 'TUN', 'TUR', 'UAE', 'UGA', 'UKR', 'URU', 'USA', 'UZB',
    'VAN', 'VEN', 'VGB', 'VIE', 'VIN', 'WAL', 'YEM', 'ZAM', 'ZAN', 'ZIM',
]

# Nombre EXACTO del dataset de Kaggle/ESPN (clave del mapeo de fixtures).
TEAM_NAMES_EN = {
    'AFG': 'Afghanistan',
    'ALB': 'Albania',
    'ALG': 'Algeria',
    'AND': 'Andorra',
    'ANG': 'Angola',
    'ARG': 'Argentina',
    'ARM': 'Armenia',
    'ATG': 'Antigua and Barbuda',
    'AUS': 'Australia',
    'AUT': 'Austria',
    'AZE': 'Azerbaijan',
    'BAN': 'Bangladesh',
    'BDI': 'Burundi',
    'BEL': 'Belgium',
    'BEN': 'Benin',
    'BER': 'Bermuda',
    'BFA': 'Burkina Faso',
    'BHR': 'Bahrain',
    'BHU': 'Bhutan',
    'BIH': 'Bosnia and Herzegovina',
    'BLR': 'Belarus',
    'BLZ': 'Belize',
    'BOL': 'Bolivia',
    'BOT': 'Botswana',
    'BRA': 'Brazil',
    'BRB': 'Barbados',
    'BRU': 'Brunei',
    'BUL': 'Bulgaria',
    'CAM': 'Cambodia',
    'CAN': 'Canada',
    'CAY': 'Cayman Islands',
    'CGO': 'Congo',
    'CHA': 'Chad',
    'CHI': 'Chile',
    'CHN': 'China',
    'CIV': 'Ivory Coast',
    'CMR': 'Cameroon',
    'COD': 'DR Congo',
    'COL': 'Colombia',
    'COM': 'Comoros',
    'CPV': 'Cape Verde',
    'CRC': 'Costa Rica',
    'CRO': 'Croatia',
    'CTA': 'Central African Republic',
    'CUB': 'Cuba',
    'CUW': 'Curaçao',
    'CYP': 'Cyprus',
    'CZE': 'Czech Republic',
    'DEN': 'Denmark',
    'DMA': 'Dominica',
    'DOM': 'Dominican Republic',
    'ECU': 'Ecuador',
    'EGY': 'Egypt',
    'ENG': 'England',
    'EQG': 'Equatorial Guinea',
    'ESP': 'Spain',
    'EST': 'Estonia',
    'ETH': 'Ethiopia',
    'FIJ': 'Fiji',
    'FIN': 'Finland',
    'FRA': 'France',
    'FRO': 'Faroe Islands',
    'GAB': 'Gabon',
    'GAM': 'Gambia',
    'GEO': 'Georgia',
    'GER': 'Germany',
    'GGY': 'Guernsey',
    'GHA': 'Ghana',
    'GIB': 'Gibraltar',
    'GNB': 'Guinea-Bissau',
    'GPE': 'Guadeloupe',
    'GRE': 'Greece',
    'GRN': 'Grenada',
    'GUA': 'Guatemala',
    'GUI': 'Guinea',
    'GUM': 'Guam',
    'GUY': 'Guyana',
    'GYF': 'French Guiana',
    'HAI': 'Haiti',
    'HKG': 'Hong Kong',
    'HON': 'Honduras',
    'HUN': 'Hungary',
    'IDN': 'Indonesia',
    'IND': 'India',
    'IRL': 'Republic of Ireland',
    'IRN': 'Iran',
    'IRQ': 'Iraq',
    'ISL': 'Iceland',
    'ISR': 'Israel',
    'ITA': 'Italy',
    'JAM': 'Jamaica',
    'JEY': 'Jersey',
    'JOR': 'Jordan',
    'JPN': 'Japan',
    'KAZ': 'Kazakhstan',
    'KEN': 'Kenya',
    'KGZ': 'Kyrgyzstan',
    'KOR': 'South Korea',
    'KSA': 'Saudi Arabia',
    'KUW': 'Kuwait',
    'KVX': 'Kosovo',
    'LAO': 'Laos',
    'LBR': 'Liberia',
    'LBY': 'Libya',
    'LCA': 'Saint Lucia',
    'LES': 'Lesotho',
    'LIB': 'Lebanon',
    'LIE': 'Liechtenstein',
    'LTU': 'Lithuania',
    'LUX': 'Luxembourg',
    'LVA': 'Latvia',
    'MAC': 'Macau',
    'MAD': 'Madagascar',
    'MAR': 'Morocco',
    'MAS': 'Malaysia',
    'MDA': 'Moldova',
    'MDV': 'Maldives',
    'MEX': 'Mexico',
    'MKD': 'North Macedonia',
    'MLI': 'Mali',
    'MLT': 'Malta',
    'MNE': 'Montenegro',
    'MOZ': 'Mozambique',
    'MRI': 'Mauritius',
    'MTN': 'Mauritania',
    'MTQ': 'Martinique',
    'MWI': 'Malawi',
    'MYA': 'Myanmar',
    'NAM': 'Namibia',
    'NCA': 'Nicaragua',
    'NCL': 'New Caledonia',
    'NED': 'Netherlands',
    'NEP': 'Nepal',
    'NGA': 'Nigeria',
    'NIG': 'Niger',
    'NIR': 'Northern Ireland',
    'NOR': 'Norway',
    'NZL': 'New Zealand',
    'OMA': 'Oman',
    'PAK': 'Pakistan',
    'PAN': 'Panama',
    'PAR': 'Paraguay',
    'PER': 'Peru',
    'PHI': 'Philippines',
    'PLE': 'Palestine',
    'PNG': 'Papua New Guinea',
    'POL': 'Poland',
    'POR': 'Portugal',
    'PRK': 'North Korea',
    'PUR': 'Puerto Rico',
    'QAT': 'Qatar',
    'ROU': 'Romania',
    'RSA': 'South Africa',
    'RUS': 'Russia',
    'RWA': 'Rwanda',
    'SCO': 'Scotland',
    'SDN': 'Sudan',
    'SEN': 'Senegal',
    'SEY': 'Seychelles',
    'SGP': 'Singapore',
    'SKN': 'Saint Kitts and Nevis',
    'SLE': 'Sierra Leone',
    'SLV': 'El Salvador',
    'SMR': 'San Marino',
    'SOL': 'Solomon Islands',
    'SRB': 'Serbia',
    'SRI': 'Sri Lanka',
    'SUI': 'Switzerland',
    'SUR': 'Suriname',
    'SVK': 'Slovakia',
    'SVN': 'Slovenia',
    'SWE': 'Sweden',
    'SWZ': 'Eswatini',
    'SYR': 'Syria',
    'TAH': 'Tahiti',
    'TAN': 'Tanzania',
    'THA': 'Thailand',
    'TJK': 'Tajikistan',
    'TKM': 'Turkmenistan',
    'TOG': 'Togo',
    'TPE': 'Taiwan',
    'TRI': 'Trinidad and Tobago',
    'TUN': 'Tunisia',
    'TUR': 'Turkey',
    'UAE': 'United Arab Emirates',
    'UGA': 'Uganda',
    'UKR': 'Ukraine',
    'URU': 'Uruguay',
    'USA': 'United States',
    'UZB': 'Uzbekistan',
    'VAN': 'Vanuatu',
    'VEN': 'Venezuela',
    'VGB': 'British Virgin Islands',
    'VIE': 'Vietnam',
    'VIN': 'Saint Vincent and the Grenadines',
    'WAL': 'Wales',
    'YEM': 'Yemen',
    'ZAM': 'Zambia',
    'ZAN': 'Zanzibar',
    'ZIM': 'Zimbabwe',
}

TEAM_STYLE = {
    'AFG': 'bloque_bajo',
    'ALB': 'bloque_bajo',
    'ALG': 'bloque_alto',
    'AND': 'bloque_bajo',
    'ANG': 'bloque_bajo',
    'ARG': 'bloque_alto',
    'ARM': 'bloque_bajo',
    'ATG': 'bloque_bajo',
    'AUS': 'bloque_alto',
    'AUT': 'bloque_alto',
    'AZE': 'bloque_bajo',
    'BAN': 'bloque_bajo',
    'BDI': 'bloque_bajo',
    'BEL': 'bloque_alto',
    'BEN': 'bloque_bajo',
    'BER': 'bloque_bajo',
    'BFA': 'bloque_bajo',
    'BHR': 'bloque_bajo',
    'BHU': 'bloque_bajo',
    'BIH': 'bloque_bajo',
    'BLR': 'bloque_bajo',
    'BLZ': 'bloque_bajo',
    'BOL': 'bloque_bajo',
    'BOT': 'bloque_bajo',
    'BRA': 'bloque_alto',
    'BRB': 'bloque_bajo',
    'BRU': 'bloque_bajo',
    'BUL': 'bloque_bajo',
    'CAM': 'bloque_bajo',
    'CAN': 'bloque_alto',
    'CAY': 'bloque_bajo',
    'CGO': 'bloque_bajo',
    'CHA': 'bloque_bajo',
    'CHI': 'bloque_alto',
    'CHN': 'bloque_bajo',
    'CIV': 'bloque_alto',
    'CMR': 'bloque_bajo',
    'COD': 'bloque_alto',
    'COL': 'bloque_alto',
    'COM': 'bloque_bajo',
    'CPV': 'bloque_bajo',
    'CRC': 'bloque_bajo',
    'CRO': 'bloque_alto',
    'CTA': 'bloque_bajo',
    'CUB': 'bloque_bajo',
    'CUW': 'bloque_bajo',
    'CYP': 'bloque_bajo',
    'CZE': 'bloque_alto',
    'DEN': 'bloque_alto',
    'DMA': 'bloque_bajo',
    'DOM': 'bloque_bajo',
    'ECU': 'bloque_alto',
    'EGY': 'bloque_alto',
    'ENG': 'bloque_alto',
    'EQG': 'bloque_bajo',
    'ESP': 'bloque_alto',
    'EST': 'bloque_bajo',
    'ETH': 'bloque_bajo',
    'FIJ': 'bloque_bajo',
    'FIN': 'bloque_bajo',
    'FRA': 'bloque_alto',
    'FRO': 'bloque_bajo',
    'GAB': 'bloque_bajo',
    'GAM': 'bloque_bajo',
    'GEO': 'bloque_bajo',
    'GER': 'bloque_alto',
    'GGY': 'bloque_alto',
    'GHA': 'bloque_bajo',
    'GIB': 'bloque_bajo',
    'GNB': 'bloque_bajo',
    'GPE': 'bloque_bajo',
    'GRE': 'bloque_alto',
    'GRN': 'bloque_bajo',
    'GUA': 'bloque_bajo',
    'GUI': 'bloque_bajo',
    'GUM': 'bloque_bajo',
    'GUY': 'bloque_bajo',
    'GYF': 'bloque_bajo',
    'HAI': 'bloque_bajo',
    'HKG': 'bloque_bajo',
    'HON': 'bloque_bajo',
    'HUN': 'bloque_alto',
    'IDN': 'bloque_bajo',
    'IND': 'bloque_bajo',
    'IRL': 'bloque_alto',
    'IRN': 'bloque_alto',
    'IRQ': 'bloque_bajo',
    'ISL': 'bloque_bajo',
    'ISR': 'bloque_bajo',
    'ITA': 'bloque_alto',
    'JAM': 'bloque_bajo',
    'JEY': 'bloque_alto',
    'JOR': 'bloque_bajo',
    'JPN': 'bloque_alto',
    'KAZ': 'bloque_bajo',
    'KEN': 'bloque_bajo',
    'KGZ': 'bloque_bajo',
    'KOR': 'bloque_alto',
    'KSA': 'bloque_bajo',
    'KUW': 'bloque_bajo',
    'KVX': 'bloque_bajo',
    'LAO': 'bloque_bajo',
    'LBR': 'bloque_bajo',
    'LBY': 'bloque_bajo',
    'LCA': 'bloque_bajo',
    'LES': 'bloque_bajo',
    'LIB': 'bloque_bajo',
    'LIE': 'bloque_bajo',
    'LTU': 'bloque_bajo',
    'LUX': 'bloque_bajo',
    'LVA': 'bloque_bajo',
    'MAC': 'bloque_bajo',
    'MAD': 'bloque_bajo',
    'MAR': 'bloque_alto',
    'MAS': 'bloque_bajo',
    'MDA': 'bloque_bajo',
    'MDV': 'bloque_bajo',
    'MEX': 'bloque_alto',
    'MKD': 'bloque_bajo',
    'MLI': 'bloque_bajo',
    'MLT': 'bloque_bajo',
    'MNE': 'bloque_bajo',
    'MOZ': 'bloque_bajo',
    'MRI': 'bloque_bajo',
    'MTN': 'bloque_bajo',
    'MTQ': 'bloque_bajo',
    'MWI': 'bloque_bajo',
    'MYA': 'bloque_bajo',
    'NAM': 'bloque_bajo',
    'NCA': 'bloque_bajo',
    'NCL': 'bloque_bajo',
    'NED': 'bloque_alto',
    'NEP': 'bloque_bajo',
    'NGA': 'bloque_alto',
    'NIG': 'bloque_bajo',
    'NIR': 'bloque_bajo',
    'NOR': 'bloque_alto',
    'NZL': 'bloque_bajo',
    'OMA': 'bloque_bajo',
    'PAK': 'bloque_bajo',
    'PAN': 'bloque_alto',
    'PAR': 'bloque_alto',
    'PER': 'bloque_bajo',
    'PHI': 'bloque_bajo',
    'PLE': 'bloque_bajo',
    'PNG': 'bloque_bajo',
    'POL': 'bloque_alto',
    'POR': 'bloque_alto',
    'PRK': 'bloque_bajo',
    'PUR': 'bloque_bajo',
    'QAT': 'bloque_bajo',
    'ROU': 'bloque_bajo',
    'RSA': 'bloque_bajo',
    'RUS': 'bloque_alto',
    'RWA': 'bloque_bajo',
    'SCO': 'bloque_alto',
    'SDN': 'bloque_bajo',
    'SEN': 'bloque_alto',
    'SEY': 'bloque_bajo',
    'SGP': 'bloque_bajo',
    'SKN': 'bloque_bajo',
    'SLE': 'bloque_bajo',
    'SLV': 'bloque_bajo',
    'SMR': 'bloque_bajo',
    'SOL': 'bloque_bajo',
    'SRB': 'bloque_alto',
    'SRI': 'bloque_bajo',
    'SUI': 'bloque_alto',
    'SUR': 'bloque_bajo',
    'SVK': 'bloque_bajo',
    'SVN': 'bloque_bajo',
    'SWE': 'bloque_alto',
    'SWZ': 'bloque_bajo',
    'SYR': 'bloque_bajo',
    'TAH': 'bloque_bajo',
    'TAN': 'bloque_bajo',
    'THA': 'bloque_bajo',
    'TJK': 'bloque_bajo',
    'TKM': 'bloque_bajo',
    'TOG': 'bloque_bajo',
    'TPE': 'bloque_bajo',
    'TRI': 'bloque_bajo',
    'TUN': 'bloque_bajo',
    'TUR': 'bloque_alto',
    'UAE': 'bloque_bajo',
    'UGA': 'bloque_bajo',
    'UKR': 'bloque_alto',
    'URU': 'bloque_alto',
    'USA': 'bloque_alto',
    'UZB': 'bloque_alto',
    'VAN': 'bloque_bajo',
    'VEN': 'bloque_alto',
    'VGB': 'bloque_bajo',
    'VIE': 'bloque_bajo',
    'VIN': 'bloque_bajo',
    'WAL': 'bloque_bajo',
    'YEM': 'bloque_bajo',
    'ZAM': 'bloque_bajo',
    'ZAN': 'bloque_bajo',
    'ZIM': 'bloque_bajo',
}

# Nombre en español para la interfaz.
TEAM_NAMES_ES = {
    'AFG': 'Afganistán',
    'ALB': 'Albania',
    'ALG': 'Algeria',
    'AND': 'Andorra',
    'ANG': 'Angola',
    'ARG': 'Argentina',
    'ARM': 'Armenia',
    'ATG': 'Antigua y Barbuda',
    'AUS': 'Australia',
    'AUT': 'Austria',
    'AZE': 'Azerbaiyán',
    'BAN': 'Bangladés',
    'BDI': 'Burundi',
    'BEL': 'Belgium',
    'BEN': 'Benín',
    'BER': 'Bermudas',
    'BFA': 'Burkina Faso',
    'BHR': 'Baréin',
    'BHU': 'Bután',
    'BIH': 'Bosnia y Herzegovina',
    'BLR': 'Bielorrusia',
    'BLZ': 'Belice',
    'BOL': 'Bolivia',
    'BOT': 'Botsuana',
    'BRA': 'Brazil',
    'BRB': 'Barbados',
    'BRU': 'Brunéi',
    'BUL': 'Bulgaria',
    'CAM': 'Camboya',
    'CAN': 'Canada',
    'CAY': 'Islas Caimán',
    'CGO': 'Congo',
    'CHA': 'Chad',
    'CHI': 'Chile',
    'CHN': 'China',
    'CIV': 'Ivory Coast',
    'CMR': 'Cameroon',
    'COD': 'RD Congo',
    'COL': 'Colombia',
    'COM': 'Comoras',
    'CPV': 'Cape Verde',
    'CRC': 'Costa Rica',
    'CRO': 'Croatia',
    'CTA': 'República Centroafricana',
    'CUB': 'Cuba',
    'CUW': 'Curazao',
    'CYP': 'Chipre',
    'CZE': 'Chequia',
    'DEN': 'Denmark',
    'DMA': 'Dominica',
    'DOM': 'República Dominicana',
    'ECU': 'Ecuador',
    'EGY': 'Egypt',
    'ENG': 'England',
    'EQG': 'Guinea Ecuatorial',
    'ESP': 'Spain',
    'EST': 'Estonia',
    'ETH': 'Etiopía',
    'FIJ': 'Fiyi',
    'FIN': 'Finlandia',
    'FRA': 'France',
    'FRO': 'Islas Feroe',
    'GAB': 'Gabón',
    'GAM': 'Gambia',
    'GEO': 'Georgia',
    'GER': 'Germany',
    'GGY': 'Guernsey',
    'GHA': 'Ghana',
    'GIB': 'Gibraltar',
    'GNB': 'Guinea-Bisáu',
    'GPE': 'Guadalupe',
    'GRE': 'Grecia',
    'GRN': 'Granada',
    'GUA': 'Guatemala',
    'GUI': 'Guinea',
    'GUM': 'Guam',
    'GUY': 'Guyana',
    'GYF': 'Guayana Francesa',
    'HAI': 'Haití',
    'HKG': 'Hong Kong',
    'HON': 'Honduras',
    'HUN': 'Hungría',
    'IDN': 'Indonesia',
    'IND': 'India',
    'IRL': 'Irlanda',
    'IRN': 'Iran',
    'IRQ': 'Irak',
    'ISL': 'Islandia',
    'ISR': 'Israel',
    'ITA': 'Italy',
    'JAM': 'Jamaica',
    'JEY': 'Jersey',
    'JOR': 'Jordan',
    'JPN': 'Japan',
    'KAZ': 'Kazajistán',
    'KEN': 'Kenia',
    'KGZ': 'Kirguistán',
    'KOR': 'South Korea',
    'KSA': 'Saudi Arabia',
    'KUW': 'Kuwait',
    'KVX': 'Kosovo',
    'LAO': 'Laos',
    'LBR': 'Liberia',
    'LBY': 'Libia',
    'LCA': 'Santa Lucía',
    'LES': 'Lesoto',
    'LIB': 'Líbano',
    'LIE': 'Liechtenstein',
    'LTU': 'Lituania',
    'LUX': 'Luxemburgo',
    'LVA': 'Letonia',
    'MAC': 'Macao',
    'MAD': 'Madagascar',
    'MAR': 'Morocco',
    'MAS': 'Malasia',
    'MDA': 'Moldavia',
    'MDV': 'Maldivas',
    'MEX': 'Mexico',
    'MKD': 'Macedonia del Norte',
    'MLI': 'Malí',
    'MLT': 'Malta',
    'MNE': 'Montenegro',
    'MOZ': 'Mozambique',
    'MRI': 'Mauricio',
    'MTN': 'Mauritania',
    'MTQ': 'Martinica',
    'MWI': 'Malaui',
    'MYA': 'Myanmar',
    'NAM': 'Namibia',
    'NCA': 'Nicaragua',
    'NCL': 'Nueva Caledonia',
    'NED': 'Netherlands',
    'NEP': 'Nepal',
    'NGA': 'Nigeria',
    'NIG': 'Níger',
    'NIR': 'Irlanda del Norte',
    'NOR': 'Norway',
    'NZL': 'New Zealand',
    'OMA': 'Omán',
    'PAK': 'Pakistán',
    'PAN': 'Panama',
    'PAR': 'Paraguay',
    'PER': 'Peru',
    'PHI': 'Filipinas',
    'PLE': 'Palestina',
    'PNG': 'Papúa Nueva Guinea',
    'POL': 'Polonia',
    'POR': 'Portugal',
    'PRK': 'Corea del Norte',
    'PUR': 'Puerto Rico',
    'QAT': 'Qatar',
    'ROU': 'Rumanía',
    'RSA': 'Sudáfrica',
    'RUS': 'Rusia',
    'RWA': 'Ruanda',
    'SCO': 'Scotland',
    'SDN': 'Sudán',
    'SEN': 'Senegal',
    'SEY': 'Seychelles',
    'SGP': 'Singapur',
    'SKN': 'San Cristóbal y Nieves',
    'SLE': 'Sierra Leona',
    'SLV': 'El Salvador',
    'SMR': 'San Marino',
    'SOL': 'Islas Salomón',
    'SRB': 'Serbia',
    'SRI': 'Sri Lanka',
    'SUI': 'Switzerland',
    'SUR': 'Surinam',
    'SVK': 'Eslovaquia',
    'SVN': 'Eslovenia',
    'SWE': 'Suecia',
    'SWZ': 'Esuatini',
    'SYR': 'Siria',
    'TAH': 'Tahití',
    'TAN': 'Tanzania',
    'THA': 'Tailandia',
    'TJK': 'Tayikistán',
    'TKM': 'Turkmenistán',
    'TOG': 'Togo',
    'TPE': 'Taipéi Chino',
    'TRI': 'Trinidad y Tobago',
    'TUN': 'Tunisia',
    'TUR': 'Turquía',
    'UAE': 'Emiratos Árabes Unidos',
    'UGA': 'Uganda',
    'UKR': 'Ucrania',
    'URU': 'Uruguay',
    'USA': 'United States',
    'UZB': 'Uzbekistan',
    'VAN': 'Vanuatu',
    'VEN': 'Venezuela',
    'VGB': 'Islas Vírgenes Británicas',
    'VIE': 'Vietnam',
    'VIN': 'San Vicente y las Granadinas',
    'WAL': 'Gales',
    'YEM': 'Yemen',
    'ZAM': 'Zambia',
    'ZAN': 'Zanzíbar',
    'ZIM': 'Zimbabue',
}

# Partidos en el histórico (insumo de la feature NIVEL_DATOS y de la UI).
TEAM_PARTIDOS = {
    'AFG': 126,
    'ALB': 311,
    'ALG': 397,
    'AND': 229,
    'ANG': 350,
    'ARG': 475,
    'ARM': 271,
    'ATG': 199,
    'AUS': 386,
    'AUT': 346,
    'AZE': 309,
    'BAN': 230,
    'BDI': 201,
    'BEL': 380,
    'BEN': 242,
    'BER': 159,
    'BFA': 373,
    'BHR': 463,
    'BHU': 101,
    'BIH': 287,
    'BLR': 301,
    'BLZ': 120,
    'BOL': 356,
    'BOT': 313,
    'BRA': 535,
    'BRB': 217,
    'BRU': 103,
    'BUL': 343,
    'CAM': 206,
    'CAN': 336,
    'CAY': 117,
    'CGO': 236,
    'CHA': 109,
    'CHI': 424,
    'CHN': 444,
    'CIV': 416,
    'CMR': 429,
    'COD': 346,
    'COL': 456,
    'COM': 145,
    'CPV': 204,
    'CRC': 515,
    'CRO': 382,
    'CTA': 105,
    'CUB': 276,
    'CUW': 179,
    'CYP': 311,
    'CZE': 363,
    'DEN': 392,
    'DMA': 149,
    'DOM': 151,
    'ECU': 413,
    'EGY': 515,
    'ENG': 437,
    'EQG': 162,
    'ESP': 447,
    'EST': 430,
    'ETH': 253,
    'FIJ': 178,
    'FIN': 396,
    'FRA': 457,
    'FRO': 263,
    'GAB': 313,
    'GAM': 177,
    'GEO': 306,
    'GER': 485,
    'GGY': 113,
    'GHA': 423,
    'GIB': 159,
    'GNB': 139,
    'GPE': 171,
    'GRE': 380,
    'GRN': 201,
    'GUA': 364,
    'GUI': 306,
    'GUM': 117,
    'GUY': 184,
    'GYF': 136,
    'HAI': 302,
    'HKG': 253,
    'HON': 467,
    'HUN': 374,
    'IDN': 346,
    'IND': 302,
    'IRL': 379,
    'IRN': 455,
    'IRQ': 436,
    'ISL': 367,
    'ISR': 308,
    'ITA': 433,
    'JAM': 512,
    'JEY': 122,
    'JOR': 430,
    'JPN': 527,
    'KAZ': 268,
    'KEN': 386,
    'KGZ': 189,
    'KOR': 557,
    'KSA': 580,
    'KUW': 470,
    'KVX': 106,
    'LAO': 185,
    'LBR': 201,
    'LBY': 248,
    'LCA': 183,
    'LES': 264,
    'LIB': 300,
    'LIE': 253,
    'LTU': 345,
    'LUX': 291,
    'LVA': 353,
    'MAC': 121,
    'MAD': 227,
    'MAR': 410,
    'MAS': 367,
    'MDA': 298,
    'MDV': 219,
    'MEX': 661,
    'MKD': 306,
    'MLI': 385,
    'MLT': 338,
    'MNE': 167,
    'MOZ': 325,
    'MRI': 218,
    'MTN': 200,
    'MTQ': 215,
    'MWI': 377,
    'MYA': 258,
    'NAM': 278,
    'NCA': 177,
    'NCL': 152,
    'NED': 428,
    'NEP': 212,
    'NGA': 418,
    'NIG': 199,
    'NIR': 305,
    'NOR': 400,
    'NZL': 237,
    'OMA': 476,
    'PAK': 160,
    'PAN': 405,
    'PAR': 401,
    'PER': 389,
    'PHI': 250,
    'PLE': 224,
    'PNG': 103,
    'POL': 445,
    'POR': 418,
    'PRK': 275,
    'PUR': 122,
    'QAT': 504,
    'ROU': 395,
    'RSA': 458,
    'RUS': 388,
    'RWA': 270,
    'SCO': 335,
    'SDN': 342,
    'SEN': 420,
    'SEY': 153,
    'SGP': 380,
    'SKN': 213,
    'SLE': 194,
    'SLV': 408,
    'SMR': 225,
    'SOL': 176,
    'SRB': 347,
    'SRI': 208,
    'SUI': 387,
    'SUR': 189,
    'SVK': 353,
    'SVN': 317,
    'SWE': 464,
    'SWZ': 253,
    'SYR': 371,
    'TAH': 144,
    'TAN': 368,
    'THA': 458,
    'TJK': 201,
    'TKM': 175,
    'TOG': 308,
    'TPE': 150,
    'TRI': 461,
    'TUN': 457,
    'TUR': 400,
    'UAE': 488,
    'UGA': 405,
    'UKR': 335,
    'URU': 425,
    'USA': 623,
    'UZB': 357,
    'VAN': 151,
    'VEN': 367,
    'VGB': 119,
    'VIE': 294,
    'VIN': 173,
    'WAL': 309,
    'YEM': 232,
    'ZAM': 509,
    'ZAN': 102,
    'ZIM': 365,
}

# ELO final replayando el histórico. Lo usa el generador sintético para
# estimar el "tier" de las selecciones que no están en su tabla manual:
# sin esto, las 151 nuevas compartían todas el tier por defecto 0.5 y el
# aumento de datos generaba partidos irrealmente parejos.
TEAM_ELO = {
    'AFG': 1257.1,
    'ALB': 1596.0,
    'ALG': 1796.7,
    'AND': 1157.9,
    'ANG': 1541.2,
    'ARG': 2088.4,
    'ARM': 1421.0,
    'ATG': 1230.5,
    'AUS': 1834.5,
    'AUT': 1782.8,
    'AZE': 1388.8,
    'BAN': 1238.6,
    'BDI': 1378.0,
    'BEL': 1881.6,
    'BEN': 1529.5,
    'BER': 1385.0,
    'BFA': 1629.9,
    'BHR': 1531.4,
    'BHU': 1026.8,
    'BIH': 1634.3,
    'BLR': 1510.9,
    'BLZ': 1323.4,
    'BOL': 1661.6,
    'BOT': 1412.5,
    'BRA': 1929.7,
    'BRB': 1208.6,
    'BRU': 1081.3,
    'BUL': 1508.5,
    'CAM': 1187.2,
    'CAN': 1790.1,
    'CAY': 1194.0,
    'CGO': 1353.8,
    'CHA': 1267.0,
    'CHI': 1699.6,
    'CHN': 1564.3,
    'CIV': 1768.4,
    'CMR': 1667.6,
    'COD': 1722.3,
    'COL': 1932.0,
    'COM': 1455.3,
    'CPV': 1658.6,
    'CRC': 1685.1,
    'CRO': 1860.6,
    'CTA': 1359.3,
    'CUB': 1423.1,
    'CUW': 1572.6,
    'CYP': 1381.3,
    'CZE': 1692.6,
    'DEN': 1812.5,
    'DMA': 1230.8,
    'DOM': 1475.5,
    'ECU': 1863.0,
    'EGY': 1773.2,
    'ENG': 1988.9,
    'EQG': 1450.8,
    'ESP': 2095.2,
    'EST': 1413.1,
    'ETH': 1403.5,
    'FIJ': 1448.4,
    'FIN': 1540.7,
    'FRA': 2032.4,
    'FRO': 1407.8,
    'GAB': 1542.9,
    'GAM': 1490.3,
    'GEO': 1608.7,
    'GER': 1901.2,
    'GGY': 1691.5,
    'GHA': 1634.9,
    'GIB': 1157.6,
    'GNB': 1379.1,
    'GPE': 1521.5,
    'GRE': 1702.7,
    'GRN': 1341.3,
    'GUA': 1608.3,
    'GUI': 1512.5,
    'GUM': 1098.1,
    'GUY': 1478.1,
    'GYF': 1423.2,
    'HAI': 1608.1,
    'HKG': 1374.9,
    'HON': 1646.1,
    'HUN': 1721.0,
    'IDN': 1526.8,
    'IND': 1315.1,
    'IRL': 1695.7,
    'IRN': 1822.8,
    'IRQ': 1689.3,
    'ISL': 1559.1,
    'ISR': 1598.2,
    'ITA': 1845.1,
    'JAM': 1632.6,
    'JEY': 1755.8,
    'JOR': 1675.1,
    'JPN': 1893.9,
    'KAZ': 1471.8,
    'KEN': 1465.3,
    'KGZ': 1493.8,
    'KOR': 1798.5,
    'KSA': 1687.0,
    'KUW': 1503.8,
    'KVX': 1684.1,
    'LAO': 1100.6,
    'LBR': 1426.5,
    'LBY': 1526.6,
    'LCA': 1309.3,
    'LES': 1406.6,
    'LIB': 1453.1,
    'LIE': 1054.6,
    'LTU': 1310.7,
    'LUX': 1419.3,
    'LVA': 1326.9,
    'MAC': 1019.5,
    'MAD': 1495.1,
    'MAR': 1935.5,
    'MAS': 1535.8,
    'MDA': 1312.7,
    'MDV': 1127.0,
    'MEX': 1918.9,
    'MKD': 1592.8,
    'MLI': 1645.0,
    'MLT': 1357.0,
    'MNE': 1493.0,
    'MOZ': 1487.2,
    'MRI': 1268.8,
    'MTN': 1447.7,
    'MTQ': 1469.2,
    'MWI': 1411.4,
    'MYA': 1244.9,
    'NAM': 1410.2,
    'NCA': 1495.5,
    'NCL': 1549.0,
    'NED': 1923.5,
    'NEP': 1201.3,
    'NGA': 1771.9,
    'NIG': 1468.8,
    'NIR': 1576.1,
    'NOR': 1890.0,
    'NZL': 1648.1,
    'OMA': 1595.2,
    'PAK': 1188.0,
    'PAN': 1701.7,
    'PAR': 1820.9,
    'PER': 1677.6,
    'PHI': 1390.5,
    'PLE': 1559.1,
    'PNG': 1481.0,
    'POL': 1724.8,
    'POR': 1923.7,
    'PRK': 1488.0,
    'PUR': 1414.1,
    'QAT': 1589.3,
    'ROU': 1614.6,
    'RSA': 1655.6,
    'RUS': 1776.9,
    'RWA': 1456.1,
    'SCO': 1747.8,
    'SDN': 1456.5,
    'SEN': 1784.9,
    'SEY': 1070.8,
    'SGP': 1375.8,
    'SKN': 1341.7,
    'SLE': 1452.3,
    'SLV': 1484.1,
    'SMR': 953.1,
    'SOL': 1402.8,
    'SRB': 1708.7,
    'SRI': 1138.2,
    'SUI': 1866.9,
    'SUR': 1563.7,
    'SVK': 1650.1,
    'SVN': 1662.4,
    'SWE': 1719.1,
    'SWZ': 1314.2,
    'SYR': 1556.5,
    'TAH': 1507.2,
    'TAN': 1398.3,
    'THA': 1560.4,
    'TJK': 1458.3,
    'TKM': 1419.1,
    'TOG': 1476.3,
    'TPE': 1167.5,
    'TRI': 1520.8,
    'TUN': 1653.7,
    'TUR': 1837.5,
    'UAE': 1649.0,
    'UGA': 1519.8,
    'UKR': 1729.4,
    'URU': 1812.9,
    'USA': 1826.8,
    'UZB': 1727.9,
    'VAN': 1465.8,
    'VEN': 1725.8,
    'VGB': 1129.3,
    'VIE': 1538.2,
    'VIN': 1371.5,
    'WAL': 1687.1,
    'YEM': 1342.1,
    'ZAM': 1510.4,
    'ZAN': 1538.8,
    'ZIM': 1431.5,
}

# Alias con los que otras fuentes publican al equipo (mapeo EXACTO,
# imprescindible con 200 selecciones para que el fuzzy no confunda
# Congo/RD Congo, Guinea/Guinea Ecuatorial, Sudán/Sudán del Sur...).
TEAM_ALIAS = {
    'AFG': ['Afghanistan'],
    'ALB': ['Albania'],
    'ALG': ['Algeria'],
    'AND': ['Andorra'],
    'ANG': ['Angola'],
    'ARG': ['Argentina'],
    'ARM': ['Armenia'],
    'ATG': ['Antigua & Barbuda', 'Antigua and Barbuda'],
    'AUS': ['Australia'],
    'AUT': ['Austria'],
    'AZE': ['Azerbaijan'],
    'BAN': ['Bangladesh'],
    'BDI': ['Burundi'],
    'BEL': ['Belgium'],
    'BEN': ['Benin'],
    'BER': ['Bermuda'],
    'BFA': ['Burkina Faso'],
    'BHR': ['Bahrain'],
    'BHU': ['Bhutan'],
    'BIH': ['Bosnia & Herzegovina', 'Bosnia and Herzegovina', 'Bosnia-Herzegovina'],
    'BLR': ['Belarus'],
    'BLZ': ['Belize'],
    'BOL': ['Bolivia'],
    'BOT': ['Botswana'],
    'BRA': ['Brazil'],
    'BRB': ['Barbados'],
    'BRU': ['Brunei'],
    'BUL': ['Bulgaria'],
    'CAM': ['Cambodia'],
    'CAN': ['Canada'],
    'CAY': ['Cayman Islands'],
    'CGO': ['Congo', 'Congo Republic', 'Congo-Brazzaville'],
    'CHA': ['Chad'],
    'CHI': ['Chile'],
    'CHN': ['China', 'China PR'],
    'CIV': ['Cote dIvoire', "Côte d'Ivoire", 'Ivory Coast'],
    'CMR': ['Cameroon'],
    'COD': ['Congo DR', 'Congo-Kinshasa', 'DR Congo', 'Democratic Republic of the Congo'],
    'COL': ['Colombia'],
    'COM': ['Comoros'],
    'CPV': ['Cabo Verde', 'Cape Verde'],
    'CRC': ['Costa Rica'],
    'CRO': ['Croatia'],
    'CTA': ['Central African Republic'],
    'CUB': ['Cuba'],
    'CUW': ['Curacao', 'Curaçao'],
    'CYP': ['Cyprus'],
    'CZE': ['Czech Republic', 'Czechia'],
    'DEN': ['Denmark'],
    'DMA': ['Dominica'],
    'DOM': ['Dominican Republic'],
    'ECU': ['Ecuador'],
    'EGY': ['Egypt'],
    'ENG': ['England'],
    'EQG': ['Equatorial Guinea'],
    'ESP': ['Spain'],
    'EST': ['Estonia'],
    'ETH': ['Ethiopia'],
    'FIJ': ['Fiji'],
    'FIN': ['Finland'],
    'FRA': ['France'],
    'FRO': ['Faroe Islands'],
    'GAB': ['Gabon'],
    'GAM': ['Gambia'],
    'GEO': ['Georgia'],
    'GER': ['Germany'],
    'GGY': ['Guernsey'],
    'GHA': ['Ghana'],
    'GIB': ['Gibraltar'],
    'GNB': ['Guinea Bissau', 'Guinea-Bissau'],
    'GPE': ['Guadeloupe'],
    'GRE': ['Greece'],
    'GRN': ['Grenada'],
    'GUA': ['Guatemala'],
    'GUI': ['Guinea'],
    'GUM': ['Guam'],
    'GUY': ['Guyana'],
    'GYF': ['French Guiana'],
    'HAI': ['Haiti'],
    'HKG': ['Hong Kong'],
    'HON': ['Honduras'],
    'HUN': ['Hungary'],
    'IDN': ['Indonesia'],
    'IND': ['India'],
    'IRL': ['Ireland', 'Rep. of Ireland', 'Republic of Ireland'],
    'IRN': ['IR Iran', 'Iran'],
    'IRQ': ['Iraq'],
    'ISL': ['Iceland'],
    'ISR': ['Israel'],
    'ITA': ['Italy'],
    'JAM': ['Jamaica'],
    'JEY': ['Jersey'],
    'JOR': ['Jordan'],
    'JPN': ['Japan'],
    'KAZ': ['Kazakhstan'],
    'KEN': ['Kenya'],
    'KGZ': ['Kyrgyzstan'],
    'KOR': ['Korea Republic', 'South Korea'],
    'KSA': ['Saudi Arabia'],
    'KUW': ['Kuwait'],
    'KVX': ['Kosovo'],
    'LAO': ['Laos'],
    'LBR': ['Liberia'],
    'LBY': ['Libya'],
    'LCA': ['Saint Lucia', 'St. Lucia'],
    'LES': ['Lesotho'],
    'LIB': ['Lebanon'],
    'LIE': ['Liechtenstein'],
    'LTU': ['Lithuania'],
    'LUX': ['Luxembourg'],
    'LVA': ['Latvia'],
    'MAC': ['Macau'],
    'MAD': ['Madagascar'],
    'MAR': ['Morocco'],
    'MAS': ['Malaysia'],
    'MDA': ['Moldova'],
    'MDV': ['Maldives'],
    'MEX': ['Mexico'],
    'MKD': ['FYR Macedonia', 'Macedonia', 'North Macedonia'],
    'MLI': ['Mali'],
    'MLT': ['Malta'],
    'MNE': ['Montenegro'],
    'MOZ': ['Mozambique'],
    'MRI': ['Mauritius'],
    'MTN': ['Mauritania'],
    'MTQ': ['Martinique'],
    'MWI': ['Malawi'],
    'MYA': ['Myanmar'],
    'NAM': ['Namibia'],
    'NCA': ['Nicaragua'],
    'NCL': ['New Caledonia'],
    'NED': ['Holland', 'Netherlands'],
    'NEP': ['Nepal'],
    'NGA': ['Nigeria'],
    'NIG': ['Niger'],
    'NIR': ['Northern Ireland'],
    'NOR': ['Norway'],
    'NZL': ['New Zealand'],
    'OMA': ['Oman'],
    'PAK': ['Pakistan'],
    'PAN': ['Panama'],
    'PAR': ['Paraguay'],
    'PER': ['Peru'],
    'PHI': ['Philippines'],
    'PLE': ['Palestine'],
    'PNG': ['Papua New Guinea'],
    'POL': ['Poland'],
    'POR': ['Portugal'],
    'PRK': ['Korea DPR', 'Korea Republic DPR', 'North Korea'],
    'PUR': ['Puerto Rico'],
    'QAT': ['Qatar'],
    'ROU': ['Romania'],
    'RSA': ['South Africa'],
    'RUS': ['Russia'],
    'RWA': ['Rwanda'],
    'SCO': ['Scotland'],
    'SDN': ['Sudan'],
    'SEN': ['Senegal'],
    'SEY': ['Seychelles'],
    'SGP': ['Singapore'],
    'SKN': ['Saint Kitts and Nevis', 'St. Kitts & Nevis'],
    'SLE': ['Sierra Leone'],
    'SLV': ['El Salvador'],
    'SMR': ['San Marino'],
    'SOL': ['Solomon Islands'],
    'SRB': ['Serbia'],
    'SRI': ['Sri Lanka'],
    'SUI': ['Switzerland'],
    'SUR': ['Suriname'],
    'SVK': ['Slovakia'],
    'SVN': ['Slovenia'],
    'SWE': ['Sweden'],
    'SWZ': ['Eswatini', 'Swaziland'],
    'SYR': ['Syria'],
    'TAH': ['Tahiti'],
    'TAN': ['Tanzania'],
    'THA': ['Thailand'],
    'TJK': ['Tajikistan'],
    'TKM': ['Turkmenistan'],
    'TOG': ['Togo'],
    'TPE': ['Chinese Taipei', 'Taiwan'],
    'TRI': ['Trinidad & Tobago', 'Trinidad and Tobago'],
    'TUN': ['Tunisia'],
    'TUR': ['Turkey', 'Turkiye', 'Türkiye'],
    'UAE': ['UAE', 'United Arab Emirates'],
    'UGA': ['Uganda'],
    'UKR': ['Ukraine'],
    'URU': ['Uruguay'],
    'USA': ['USA', 'United States', 'United States of America'],
    'UZB': ['Uzbekistan'],
    'VAN': ['Vanuatu'],
    'VEN': ['Venezuela'],
    'VGB': ['British Virgin Islands'],
    'VIE': ['Vietnam'],
    'VIN': ['Saint Vincent and the Grenadines', 'St Vincent and the Grenadines', 'St. Vincent & Grenadines'],
    'WAL': ['Wales'],
    'YEM': ['Yemen'],
    'ZAM': ['Zambia'],
    'ZAN': ['Zanzibar'],
    'ZIM': ['Zimbabwe'],
}

